# configs/esg_resilience_analysis_config.yaml

file_path: '../data/esg_financial_data.csv'
esg_columns:
  - 'Environment Score'
  - 'Social Score'
  - 'Governance Score'
  - 'ESG Rating'
financial_columns:
  - 'P/E '
  - 'P/B '
  - 'EPS '
  - 'Total income'
  - 'Total assets'
  - 'Market Capitalisation / Enterprise Value'
shock_levels:
  - -0.10
  - -0.20
  - -0.30
  - 0.10
  - 0.20
